name: Непрерывная интеграция

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Актуализация
        uses: actions/checkout@v2

      - name: Установка JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx # нужен FX
          architecture: x64
          # реджестри пакетов 1С
          server-id: dt_repository
          # назначается в сборке
          server-username: MAVEN_USERNAME
          # назначается в сборке
          server-password: MAVEN_CENTRAL_TOKEN # в открытом виде в секретах 

      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven
      - name: Кеширование m2
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('target/default.target') }}
          restore-keys: ${{ runner.os }}-m2

      # https://edt.1c.ru/dev/ru/docs/plugins/project/build-install-publish-project/
      - name: Сборка
        run: |
          Xvfb :5 -screen 0 1280x1024x8 -fbdir /tmp &
          export DISPLAY=:5
          export MAVEN_OPTS=
          mvn clean dependency:copy@get-lombok
          export MAVEN_OPTS=-javaagent:target/lombok.jar=ECJ
          mvn verify -PSDK,find-bugs -Dtycho.localArtifacts=ignore
        working-directory: ./build
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
